INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Laundry", "Cleaning", 10, "Monday", "Tuesday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dishes", "Cleaning", 10, "Daily", "Never");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mow Lawn", "Yard", 20, "Saturday", "Sunday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Tree Trim", "Yard", 20, "Saturday", "Sunday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mortgage", "Finance", 30, "1st of the month", "15th of the month");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Bills", "Finance", 30, "1st of the month", "15th of the month");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Plumbing", "Maintanace", 40, "Wednesday", "Thursday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("AC cleaning", "Maintanace", 40, "Wednesday", "Thursday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Painting", "Decor", 50, "Friday", "Saturday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Tray", "Decor", 50, "Friday", "Saturday");

INSERT INTO users (name, age) VALUES ("Kam", 10);
INSERT INTO users (name, age) VALUES ("Sam", 10);
INSERT INTO users (name, age) VALUES ("Pam", 10);
INSERT INTO users (name, age) VALUES ("Tam", 10);
INSERT INTO users (name, age) VALUES ("Val", 10);
INSERT INTO users (name, age) VALUES ("Mal", 20);
INSERT INTO users (name, age) VALUES ("Bray", 20);
INSERT INTO users (name, age) VALUES ("Jay", 20);
INSERT INTO users (name, age) VALUES ("Kay", 20);
INSERT INTO users (name, age) VALUES ("Ray", 20);
INSERT INTO users (name, age) VALUES ("Sue", 30);
INSERT INTO users (name, age) VALUES ("Lou", 30);
INSERT INTO users (name, age) VALUES ("Pat", 30);
INSERT INTO users (name, age) VALUES ("Mat", 30);
INSERT INTO users (name, age) VALUES ("Mo", 30);
INSERT INTO users (name, age) VALUES ("Bo", 40);
INSERT INTO users (name, age) VALUES ("Tim", 40);
INSERT INTO users (name, age) VALUES ("Kim", 40);
INSERT INTO users (name, age) VALUES ("Jan", 40);
INSERT INTO users (name, age) VALUES ("Dan", 40);

INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 3, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 5, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 5, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 6, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 9, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 11, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 12, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 13, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 15, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 16, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 17, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15,18, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15,19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 20, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 8,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 10, 10);
